version: "3.6"
services:
  app:
    stdin_open: true
    tty: true
    environment:
      - TWILIO_ACCOUNT_SID=your_account_sid
      - TWILIO_AUTH_TOKEN=your_account_token
      - VERIFICATION_SID=VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    build: .
    ports: 
      - "8080:8080"
